
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package mt.edu.um.cs.cps2000.parseandlexer;

/** CUP generated class containing symbol constants. */
public class JParserSym {
  /* terminals */
  public static final int STRING_LITERAL = 8;
  public static final int FUNCTION = 27;
  public static final int RELATIONAL_OP = 10;
  public static final int CHAR_LITERAL = 7;
  public static final int CURLY_BRACE_OPEN = 18;
  public static final int MINUS = 12;
  public static final int WRITE = 26;
  public static final int BOOLEAN_LITERAL = 4;
  public static final int REAL_LITERAL = 6;
  public static final int NOT = 29;
  public static final int SEMICOLON = 15;
  public static final int AND = 31;
  public static final int BRACE_OPEN = 20;
  public static final int HALT = 23;
  public static final int TYPE = 2;
  public static final int IN = 34;
  public static final int OR = 30;
  public static final int COMMA = 17;
  public static final int PLUS = 11;
  public static final int IF = 35;
  public static final int EOF = 0;
  public static final int CURLY_BRACE_CLOSE = 19;
  public static final int error = 1;
  public static final int EQ = 33;
  public static final int COLON = 16;
  public static final int ELSE = 36;
  public static final int READ = 25;
  public static final int TO = 22;
  public static final int WHILE = 24;
  public static final int LET = 32;
  public static final int BRACE_CLOSE = 21;
  public static final int UNIT_LITERAL = 9;
  public static final int DIVISION = 14;
  public static final int MULTIPLICATION = 13;
  public static final int SET = 28;
  public static final int INTEGER_LITERAL = 5;
  public static final int IDENTIFIER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TYPE",
  "IDENTIFIER",
  "BOOLEAN_LITERAL",
  "INTEGER_LITERAL",
  "REAL_LITERAL",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "UNIT_LITERAL",
  "RELATIONAL_OP",
  "PLUS",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "CURLY_BRACE_OPEN",
  "CURLY_BRACE_CLOSE",
  "BRACE_OPEN",
  "BRACE_CLOSE",
  "TO",
  "HALT",
  "WHILE",
  "READ",
  "WRITE",
  "FUNCTION",
  "SET",
  "NOT",
  "OR",
  "AND",
  "LET",
  "EQ",
  "IN",
  "IF",
  "ELSE"
  };
}

